# Generated by Skyramp v1.3.13 on 2026-03-16 19:21:37.697211515 +0000 UTC m=+148.090962822
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_self_favoriting_prevention.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_self_favoriting_prevention_1742119800.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    login_POST_request_body = r'''{
        "user": {
            "email": "testbot@example.com",
            "password": "Testbot123!"
        }
    }'''
    
    # Execute Request
    login_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users/login",
        method="POST",
        body=login_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert login_POST_response.status_code == 200

    # Request Body
    articles_POST_request_body = r'''{
        "article": {
            "body": "This article is created to test that an author cannot favorite their own article.",
            "description": "A test article for self-favoriting scenario",
            "tagList": [],
            "title": "My Test Article 1742119800"
        }
    }'''
    
    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 201

    # Request Body
    favorite_POST_request_body = r'''{}'''
    
    # Execute Request
    favorite_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles/{articles}/favorite",
        method="POST",
        body=favorite_POST_request_body,
        headers=headers,
        path_params={"articles": skyramp.get_response_value(articles_POST_response, "article.slug")}
    )
    # Generated Assertions
    assert favorite_POST_response.status_code == 400


if __name__ == "__main__":
    test_integration()
