# Generated by Skyramp v1.3.13 on 2026-03-16 20:43:09.198283877 +0000 UTC m=+157.440170848
# Command: skyramp generate fuzz rest http://localhost:8000/api/articles \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_fuzz_articles_title_max_length.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"article":{"title":"Test Article Title","description":"Test description for article","body":"Test body content for the article","tagList":[]}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/articles POST
def test_articles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    articles_POST_request_body = r'''{
      "article": {
        "title": "Test Article Title",
        "description": "Test description for article",
        "body": "Test body content for the article",
        "tagList": []
      }
    }'''
    
    # Fuzz strategies
    articles_post_fuzzed_body = {"article": {
            "body": "0123456789",
            "description": "0123456789",
            "tagList": [],
            "title": "0123456789"
        }}
    # Fuzz status codes
    expected_articles_post_status_code = {"article": {
            "body": "40x",
            "description": "40x",
            "tagList": [],
            "title": "40x"
        }}
    # Fuzz status codes for Null values
    expected_articles_post_null_status_code = {"article": {
            "body": "40x",
            "description": "40x",
            "tagList": [],
            "title": "40x"
        }}

    # Execute Request
    articles_POST_response = client.send_request(
        url=URL,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(articles_post_fuzzed_body):
        # Execute Request
        articles_POST_response = client.send_request(
            url=URL,
            path="/api/articles",
            method="POST",
            body=articles_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(articles_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_articles_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(articles_post_fuzzed_body, key) }'
        )

        # Execute Request
        articles_POST_response = client.send_request(
            url=URL,
            path="/api/articles",
            method="POST",
            body=articles_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_articles_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_articles_post()
