# Generated by Skyramp v1.3.13 on 2026-03-16 21:08:55.339971094 +0000 UTC m=+194.390672634
# Command: skyramp generate contract rest http://localhost:8000/api/profiles/testbot_profile_user \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_profile_articles_count.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/profiles/testbot_profile_user GET
def test_testbot_profile_user_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_testbot_profile_user_GET_response_body = r'''{
        "profile": {
            "articlesCount": 0,
            "bio": "",
            "following": false,
            "image": "string",
            "username": "string"
        }
    }'''

    # Execute Request
    testbot_profile_user_GET_response = client.send_request(
        url=URL,
        path="/api/profiles/testbot_profile_user",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert testbot_profile_user_GET_response.status_code == 200
    assert skyramp.check_schema(testbot_profile_user_GET_response, expected_testbot_profile_user_GET_response_body)
    assert skyramp.get_response_value(testbot_profile_user_GET_response, "profile.articlesCount") is not None
    assert skyramp.get_response_value(testbot_profile_user_GET_response, "profile.bio") is not None
    assert skyramp.get_response_value(testbot_profile_user_GET_response, "profile.following") is not None


if __name__ == "__main__":
    test_testbot_profile_user_get()
