# Generated by Skyramp v1.3.13 on 2026-03-16 21:08:46.812943741 +0000 UTC m=+185.863645261
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_articles_count_profile_validation.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_articles_count_profile_validation_1742120100.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    username = "testbot_ac_1742120100"

    # Request Body
    users_POST_request_body = r'''{
        "user": {
            "email": "testbot_ac_1742120100@example.com",
            "password": "Password123!",
            "username": "testbot_ac_1742120100"
        }
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers,
        data_override={"user.username": username}
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Request Body
    login_POST_request_body = r'''{
        "user": {
            "email": "testbot_ac_1742120100@example.com",
            "password": "Password123!"
        }
    }'''
    
    # Execute Request
    login_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users/login",
        method="POST",
        body=login_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert login_POST_response.status_code == 200

    # Request Body
    articles_POST_request_body = r'''{
        "article": {
            "body": "This article is created to validate the articles_count field returned in the profile response.",
            "description": "Testing articles count in profile response",
            "tagList": [],
            "title": "Testbot Article 1742120100"
        }
    }'''
    
    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 201

    # Execute Request
    profiles_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/profiles/{profiles}",
        method="GET",
        headers=headers,
        path_params={"profiles": skyramp.get_response_value(login_POST_response, "user.username")}
    )
    # Generated Assertions
    assert profiles_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
