# Generated by Skyramp v1.3.13 on 2026-03-16 21:41:41.464191863 +0000 UTC m=+256.677575642
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_article_keyword_search.py \
# 		--output-dir /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/fastapi-realworld-example-app/fastapi-realworld-example-app/skyramp-tests/scenario_article_search_kw_1742121600.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    search = "xnonmatchingkeywordxyz1742121600"

    # Request Body
    users_POST_request_body = r'''{
        "user": {
            "email": "searchtest_1742121600@example.com",
            "password": "Password123!",
            "username": "searchtest_1742121600"
        }
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert users_POST_response.status_code == 201

    # Request Body
    login_POST_request_body = r'''{
        "user": {
            "email": "searchtest_1742121600@example.com",
            "password": "Password123!"
        }
    }'''
    
    # Execute Request
    login_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/users/login",
        method="POST",
        body=login_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert login_POST_response.status_code == 200

    # Request Body
    articles_POST_request_body = r'''{
        "article": {
            "body": "This article body contains unique keyword skyrampkw1742121600 for search validation.",
            "description": "Testing keyword search functionality",
            "tagList": [],
            "title": "Searchable Article Skyrampkw1742121600"
        }
    }'''
    
    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 201

    # Execute Request
    articles_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="GET",
        headers=headers,
        query_params={"search": ["skyrampkw1742121600"]}
    )
    # Generated Assertions
    assert articles_GET_response.status_code == 200

    # Execute Request
    articles_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="GET",
        headers=headers,
        query_params={"search": ["xnonmatchingkeywordxyz1742121600"]}
    )
    # Generated Assertions
    assert articles_GET_1_response.status_code == 200


if __name__ == "__main__":
    test_integration()
